# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170323_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadamic_record',
            name='quiz_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='acadamic_record',
            name='quiz_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cell_number',
            field=models.IntegerField(null=True),
        ),
    ]
