# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20170323_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acadamic_record',
            name='u_id',
        ),
        migrations.AlterField(
            model_name='acadamic_record',
            name='a_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='acadamic_record',
            name='quiz_marks',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='acadamic_record',
            name='quiz_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='group',
            name='comments',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='files',
            field=models.FileField(default='', max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='g_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='cell_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_id',
            field=models.CharField(max_length=40),
        ),
    ]
