# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170323_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='acadamic_record',
            name='u_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='u_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='u_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.User'),
            preserve_default=False,
        ),
    ]
