# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20170324_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='g_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
