# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
