# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20170327_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='add_photo',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='group',
            name='cover_photo',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='add_photo',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(auto_now=True, max_length=40),
        ),
    ]
