# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20170328_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
